Repository MODO-ajou/MODO_FE, pull requests merged in 2023-05, with the labels that each got.

#2 MODO-16 feat: 로그인 페이지
  package-lock.json
  package.json
  src/@types/svg.d.ts
  src/@types/vite-env.d.ts
  src/App.tsx
  src/Components/Button/index.tsx
  src/Components/Button/types.ts
  src/Components/Input/index.tsx
  src/Components/Input/types.ts
  src/assets/login-banner.svg
  src/assets/modo.svg
  src/assets/react.svg
  src/main.tsx
  src/pages/login/index.tsx
  src/styles/global.css
  tsconfig.json
  vercel.json
  vite.config.ts
Labels: 🛠 Feat, 💬 Please Review, ✒ Style

#4 MODO-40 feat: 위치인증 컴포넌트 개발
  index.html
  src/@types/map.d.ts
  src/App.tsx
  src/Components/Map/index.tsx
  src/Components/SearchBar/index.tsx
  src/Components/SearchBar/types.ts
  src/assets/location.svg
  src/assets/marker.svg
  src/assets/search.svg
  src/pages/signup2/index.tsx
Labels: 🛠 Feat, 💬 Please Review

#8 Modo 41 feat/main page
  src/App.tsx
  src/Components/Banner/index.tsx
  src/Components/BookSearchBar/index.tsx
  src/Components/BookSearchBar/types.ts
  src/Components/Header/index.tsx
  src/Components/ItemList/index.tsx
  src/Components/ItemList/types.ts
  src/Components/ItemTitle/index.tsx
  src/Components/ItemTitle/types.ts
  src/Components/SmallButton/index.tsx
  src/Components/SmallButton/smallButtonReducer.ts
  src/Components/SmallButton/types.ts
  src/Components/UserRank/index.tsx
  src/Components/UserRank/types.ts
  src/assets/ModoEventBanner.jpeg
  src/assets/arrow.svg
  src/assets/oneTHing.png
  src/assets/search.svg
  src/pages/addbook/index.tsx
  src/pages/mainpage/index.tsx
  tailwind.config.js
  tsconfig.tsbuildinfo
Labels: 🐛 Bug, 🛠 Feat, 💬 Please Review, ✒ Style
